set(STB_PATH ${PROJECT_SOURCE_DIR}/Dependencies/)
set(GLM_PATH ${PROJECT_SOURCE_DIR}/Dependencies/glm)
set(GLFW_PATH ${PROJECT_SOURCE_DIR}/Dependencies/GLFW/glfw-3.3.8.bin.WIN64)
set(VULKAN_PATH ${PROJECT_SOURCE_DIR}/Dependencies/Vulkan/1.3.268.0)
set(IMGUI_PATH ${PROJECT_SOURCE_DIR}/Dependencies/ImGui/imgui-docking)
set(ASSIMP_PATH ${PROJECT_SOURCE_DIR}/Dependencies/Assimp)
set(MESHOPTIMIZER_PATH ${PROJECT_SOURCE_DIR}/Dependencies/Meshoptimizer/src)
set(METIS_PATH ${PROJECT_SOURCE_DIR}/Dependencies/Metis)