#version 450
#extension GL_EXT_debug_printf : enable



layout (binding = 0) uniform ParameterUBO {
   mat4 model;
   mat4 view;
   mat4 proj;  
} ubo;

struct InputComputeData
{
   vec3 boundCenter;
   vec3 parentBoundCenter;
   int meshletID;
   float error;
   float parentError;
   int lod;
   int numberOfInstance;
};

struct ConstantData
{
   vec3 instancesPos;
   int numberOfMeshlet;
   int numberOfInstances;
   int width;
   float hfov;
   float errorThreshold;
};

struct OutputData
{
   int index;
   int ID;
   int instanceNumber;
};

layout(std140, binding = 3) readonly buffer SSBOInputData 
{
   InputComputeData inputComputeData[ ];
};

layout(std140, binding = 4) readonly buffer SSBOConstantData 
{
   ConstantData constantData[ ];
};

layout(std140, binding = 5) buffer SSBOSelectedData 
{
   OutputData selected[ ];
};




const int MAX_LOD_NUMBER = 5;

float ComputeScreenSpaceError(vec3 centerBound, float groupError, int width, 
float hfov, vec3 instancePos, mat4 modelView)
{
   centerBound += instancePos;
   vec4 viewCenter = vec4(centerBound, 1.0f);
   //I transform the center in view-space
   viewCenter = modelView * viewCenter;
   centerBound.x = viewCenter.x;
   centerBound.y = viewCenter.y;
   centerBound.z = viewCenter.z;
   float radius = length(vec3(modelView * vec4(groupError, 0, 0, 0 )));

   //https://stackoverflow.com/questions/21648630/radius-of-projected-sphere-in-screen-space
   const float cotHalfFov = 1.0f / tan(hfov / 2.0f);
   const float d2 = dot(centerBound, centerBound);
   const float r = radius;
   const float div = sqrt(d2 - r*r);
   float screenSpaceError = (width / 2.0f * cotHalfFov * r) / div;
   return screenSpaceError;
}

layout (local_size_x = 32) in;
void main() 
{
   debugPrintfEXT("TT");
   uint index = gl_GlobalInvocationID.x;
   if(index >= constantData[0].numberOfMeshlet * constantData[0].numberOfInstances)
      return;

   int modIndex = int(floor(index / (constantData[0].numberOfMeshlet)));
   vec3 currentInstancePos = constantData[modIndex].instancesPos;
   
   InputComputeData currentInputData = inputComputeData[index];
   mat4 modelView = ubo.view * ubo.model;

   float currentError = ComputeScreenSpaceError(currentInputData.boundCenter, currentInputData.error, constantData[0].width,
   constantData[0].hfov, currentInstancePos, modelView);
   float parentError;

   if(currentInputData.lod >= MAX_LOD_NUMBER - 1)
   {
      parentError = constantData[0].errorThreshold + 0.1f;
   }
   else
   {
      parentError = ComputeScreenSpaceError(currentInputData.parentBoundCenter, currentInputData.parentError,
      constantData[0].width, constantData[0].hfov, currentInstancePos, modelView);
   }
   

   if(currentError <= constantData[0].errorThreshold && parentError > constantData[0].errorThreshold)
   {
      int i = atomicAdd(selected[0].index, 1);
      selected[i].ID = currentInputData.meshletID;
      selected[i].instanceNumber = currentInputData.numberOfInstance;
   }
}