#version 450
#extension GL_EXT_debug_printf : enable



layout (binding = 0) uniform ParameterUBO {
   mat4 model;
   mat4 view;
   mat4 proj;  
} ubo;

struct InputComputeData
{
   vec3 boundCenter;
   vec3 parentBoundCenter;
   int meshletID;
   float error;
   float parentError;
   int lod;
   int numberOfInstance;
};

struct ConstantData
{
   vec3 instancesPos;
   int numberOfMeshlet;
   int numberOfInstances;
   int height;
   float hfov;
   float errorThreshold;
};

struct OutputData
{
   int index;
   int ID;
   int instanceNumber;
};

layout(std140, binding = 3) readonly buffer SSBOInputData 
{
   InputComputeData inputComputeData[ ];
};

layout(std140, binding = 4) readonly buffer SSBOConstantData 
{
   ConstantData constantData[ ];
};

layout(std140, binding = 5) buffer SSBOSelectedData 
{
   OutputData selected[ ];
};




const int MAX_LOD_NUMBER = 5;

float ComputeScreenSpaceError(vec3 centerBound, float groupError, int height, 
float hfov, vec3 instancePos, mat4 modelView)
{
   centerBound += instancePos;
   vec4 viewCenter = vec4(centerBound, 1.0f);

   viewCenter = modelView * viewCenter;
   centerBound.x = viewCenter.x;
   centerBound.y = viewCenter.y;
   centerBound.z = viewCenter.z; 
   float radiusErrorViewSpace = length(vec3(modelView * vec4(groupError, 0, 0, 0 )));

   //https://stackoverflow.com/questions/21648630/radius-of-projected-sphere-in-screen-space
   //https://jglrxavpok.github.io/2024/04/02/recreating-nanite-runtime-lod-selection.html#culling-at-runtime
   /*In these instructions I simply convert the radius error in screen space, obtaining
   in this way the screen space error*/

   //It is the cotangent of the half FOV. Simple cotangent formula is: 1 / tan(phi)
   const float cotHalfFov = 1.0f / tan(hfov / 2.0f);
   // ||centerBound|| * ||centerBound|| * cos(0)
   const float d2 = dot(centerBound, centerBound);
   const float r = radiusErrorViewSpace;
   //It is the distance between the eye and a point on the sphere "horizon"
   const float l = sqrt(d2 - r*r);

   //Projected radius
   const float pr = (cotHalfFov * r) / l;

   //error in screen space 
   float screenSpaceError = (height / 2.0f) * pr;
   return screenSpaceError;
}

layout (local_size_x = 32) in;
void main() 
{
   debugPrintfEXT("TT");
   uint index = gl_GlobalInvocationID.x;
   if(index >= constantData[0].numberOfMeshlet * constantData[0].numberOfInstances)
      return;

   
   
   InputComputeData currentInputData = inputComputeData[index];
   mat4 modelView = ubo.view * ubo.model;

   int instanceIndex = currentInputData.numberOfInstance;
   vec3 currentInstancePos = constantData[instanceIndex].instancesPos;

   float currentError = ComputeScreenSpaceError(currentInputData.boundCenter, currentInputData.error, constantData[0].height,
   constantData[0].hfov, currentInstancePos, modelView);
   float parentError;

   if(currentInputData.lod >= MAX_LOD_NUMBER - 1)
   {
      parentError = constantData[0].errorThreshold + 0.1f;
   }
   else
   {
      parentError = ComputeScreenSpaceError(currentInputData.parentBoundCenter, currentInputData.parentError,
      constantData[0].height, constantData[0].hfov, currentInstancePos, modelView);
   }
   

   if(currentError <= constantData[0].errorThreshold && parentError > constantData[0].errorThreshold)
   {
      int i = atomicAdd(selected[0].index, 1);
      selected[i].ID = currentInputData.meshletID;
      selected[i].instanceNumber = currentInputData.numberOfInstance;
   }
}